{{- $creds := lookup "v1" "Secret" .Release.Namespace .Values.app.in.secret -}}

{{- if not $creds }}
{{ fail "Required secret for outgoing s3 does not exist in the namespace" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "encrypt.fullname" . }}-minio-client
stringData:
  config.json: |
    {
      "version": "10",
      "aliases": {
        "fake_s3": {
          "url": "http://{{ include "encrypt.fullname" . }}",
          "accessKey": "{{ index $creds.data "accessKey" | b64dec }}",
          "secretKey": "{{ index $creds.data "secretKey" | b64dec }}",
          "api": "s3v4",
          "path": "on"
        }
      }
    }
