---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backup-cluster
  namespace: backup
spec:
  releaseName: backup-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: rook-ceph
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    clusterName: backup-cluster
    toolbox:
      enabled: false
    monitoring:
      enabled: true
    cephClusterSpec:
      dataDirHostPath: /var/lib/backup-rook
      dashboard:
        enabled: true
      storage:
        nodes:
          - name: de-man1-01
            devices:
              - name: /dev/disk/by-id/ata-WDC_WD50NDZW-11MR8S1_WD-WXR1E9990V9C
                config:
                  osdsPerDevice: "1"
                  crushDeviceClass: hdd
              - name: /dev/disk/by-id/ata-WDC_WD20NMVW-11EDZS6_WD-WX41EC5EYPN0
                config:
                  osdsPerDevice: "1"
                  crushDeviceClass: hdd
              - name: /dev/disk/by-id/ata-ST2000LM007-1R8174_WDZK4PLR
                config:
                  osdsPerDevice: "1"
                  crushDeviceClass: hdd
        config:
          encryptedDevice: "true"
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        modules:
          - name: rook
            enabled: true
          - name: rgw
      resources:
        mgr:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
        mon:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
      placement:
        all:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: workload
                      operator: In
                      values:
                        - backup
          podAffinity:
          podAntiAffinity:
          topologySpreadConstraints:
          tolerations:
            - key: workload
              operator: "Equal"
              value: "backup"
              effect: "NoSchedule"
    ingress:
      dashboard:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        tls:
          - secretName: rook-backup-tls
            hosts:
              - ceph-backup.men.sh
        hosts:
          - host: ceph-backup.men.sh
            paths:
              - path: /
                pathType: Prefix
    cephBlockPools: []
    cephFileSystems: []
    cephObjectStores:
      - name: backup-objectstore
        spec:
          metadataPool:
            failureDomain: osd
            replicated:
              size: 2
          dataPool:
            failureDomain: osd
            replicated:
              size: 2
          gateway:
            instances: 1
            port: 80
            securePort: 443
        storageClass:
          enabled: true
          name: ceph-bucket-backup
          reclaimPolicy: Delete
          volumeBindingMode: "Immediate"
          annotations: {}
          parameters:
            region: de-west-1
