---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prod-cluster
  namespace: rook-ceph
spec:
  releaseName: prod-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    clusterName: prod-cluster
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    cephClusterSpec:
      dataDirHostPath: /var/lib/prod-rook
      dashboard:
        enabled: true
      storage:
        useAllDevices: false
        useAllNodes: false
        config:
          encryptedDevice: "false"
          osdPerDevice: "1"
        nodes:
          - name: de-stg1-01
            devices:
              - name: /dev/disk/by-id/ata-ST16000NM000J-2TW103_ZR5652PC
                config:
                  crushDeviceClass: hdd
              - name: /dev/disk/by-id/ata-ST16000NM000J-2TW103_ZR55K5Z2
                config:
                  crushDeviceClass: hdd
              - name: /dev/disk/by-id/nvme-SanDisk_Extreme_Pro_500GB_20470J800180
                config:
                  crushDeviceClass: nvme
              - name: /dev/disk/by-id/dm-uuid-LVM-ARxaEYwOivrrQihUwiCDh04KVa35eM3L3yt4DInSVTNfPs8gb917tcqYvlSNbyJ2
                config:
                  crushDeviceClass: nvme
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        modules:
          - name: rook
            enabled: true
          - name: rgw
    ingress:
      dashboard:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        tls:
          - secretName: rook-tls
            hosts:
              - ceph.men.sh
        hosts:
          - host: ceph.men.sh
            paths:
              - path: /
                pathType: Prefix
    cephBlockPools:
      - name: builtin-mgr
        spec:
          name: .mgr
          failureDomain: osd
          enableCrushUpdates: true
          replicated:
            size: 3
        storageClass:
          enabled: false
    cephObjectStores: []
    cephFileSystems:
      - name: ceph-filesystem
        # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md#filesystem-settings for available configuration
        spec:
          metadataPool:
            failureDomain: osd
            deviceClass: nvme
            replicated:
              size: 2
          dataPools:
            - failureDomain: osd
              deviceClass: hdd
              replicated:
                size: 2
              name: cephfs-data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              limits:
                memory: "32Gi"
              requests:
                cpu: "1000m"
                memory: "4Gi"
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          # (Optional) specify a data pool to use, must be the name of one of the data pools above, 'data0' by default
          pool: data0
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"
          annotations: {}
          labels: {}
          mountOptions: []
          # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md#provision-storage for available configuration
          parameters:
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4
