---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prod-cluster
  namespace: rook-ceph
spec:
  releaseName: prod-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    clusterName: prod-cluster
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    cephClusterSpec:
      dataDirHostPath: /var/lib/prod-rook
      dashboard:
        enabled: true
      storage:
        nodes:
          - name: de-stg1-01
            devices:
              - name: /dev/disk/by-id/ata-ST16000NM000J-2TW103_ZR5652PC
                config:
                  osdsPerDevice: "1"
                  crushDeviceClass: hdd
              - name: /dev/disk/by-id/ata-ST16000NM000J-2TW103_ZR55K5Z2
                config:
                  osdsPerDevice: "1"
                  crushDeviceClass: hdd
        config:
          encryptedDevice: "true"
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        modules:
          - name: rook
            enabled: true
          - name: rgw
      resources:
        mgr:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
        mds:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
        mon:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
    ingress:
      dashboard:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        tls:
          - secretName: rook-tls
            hosts:
              - ceph.men.sh
        hosts:
          - host: ceph.men.sh
            paths:
              - path: /
                pathType: Prefix
    cephBlockPools: []
    cephFileSystems: []
    cephObjectStores: []
