apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - custom-charts.yaml
  - snapshots.yaml
  - cert-manager.yaml
  - weave-gitops.yaml
  - ./backup
  - cnpg.yaml
  - rook.yaml
  - ./monitoring
