apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      tls:
        - hosts:
            - media.men.sh
          secretName: media-tls
      hosts:
        - host: media.men.sh
          paths:
            - path: /
              pathType: Prefix
