apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/rook
  - ../base/nextcloud
  - rook-cluster.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
