apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/zitadel
  - ../base/headscale
#  - ../base/nextcloud
#  - ../base/jellyfin
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
  - path: zitadel-values.yaml
    target:
      kind: HelmRelease
      name: zitadel
#  - path: nextcloud-values.yaml
#    target:
#      kind: HelmRelease
#      name: nextcloud
#  - path: jellyfin-values.yaml
#    target:
#      kind: HelmRelease
#      name: jellyfin
