apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/nextcloud
  - ../base/jellyfin
  - ../base/headscale
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
  - path: nextcloud-values.yaml
    target:
      kind: HelmRelease
      name: nextcloud
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
