apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/zitadel
  - ../base/headscale
  - ../base/weave-gitops
  - ../base/monitoring
#  - ../base/nextcloud
#  - ../base/jellyfin
patches:
  - path: weave-gitops-values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
  - path: zitadel-values.yaml
    target:
      kind: HelmRelease
      name: zitadel
  - path: monitoring-values.yaml
    target:
      kind: HelmRelease
      name: prometheus
#  - path: nextcloud-values.yaml
#    target:
#      kind: HelmRelease
#      name: nextcloud
#  - path: jellyfin-values.yaml
#    target:
#      kind: HelmRelease
#      name: jellyfin
