---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  values:
    ingress:
      tls:
        - secretName: weave-tls
          hosts:
            - gitops.men.sh
      hosts:
        - host: gitops.men.sh
          paths:
            - path: /
              pathType: Prefix
