apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: default
stringData:
  token: ENC[AES256_GCM,data:3WR8QyEkSZ27p0YOE0XmUp3lA51FGV/F64B98ijjtyGOqDy91nkrsw==,iv:2ETLwfwOhRt9S5TM38XiDexA0aTSklVvqHN0Vcp4LXY=,tag:s8JxdfD+eNe+n+6ebexUTA==,type:str]
sops:
  age:
    - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZlJBOVB2M2VVR2tRWCtp
        ZCtoV3VxM295OUFWcGl3aVZubUdkTE8yZWtzCkZzbmdscktuVG1qRWJMS2pMcmhB
        VVdZTkIyQWUxZjNGS1AyL0tTdkJ3bmsKLS0tIDVQdTM5aHpmZzdtVERCVlV5UUxw
        QzdKWU4wOHZEa1lLTnFpcVd4YkQ0QncKL11nvOr/KWW1MLe5h1wHbBtNTrHhm5KD
        1XGkQm67x/StoeHkoWS8Rp1kI29t2/rg93mfMv27CuozyzS3uBVFog==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEpaVlJlMFQwWEtPbzZX
        VDVKd05sRjBLVm9xbCtQd1J0S285NzVOZURJCi9KY0pobStYbER0VW00YXo1M3Q0
        VVZaKzZNTE9VTDRteGg5d1N2R1RkUTgKLS0tIGtRanEza01aQjRTWjdJa2cxOFpx
        SURGTXJ1TVYwbmhnQTdWSnpuazB0aUUKmVDYLguDhUaEGas1KX/0ExMcwBzAj/KK
        h9MHEYcv/kHGnWciCRPIJr/YZdvybOuaq9gFiuw959kwjuy4AcWH/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:54:24Z"
  mac: ENC[AES256_GCM,data:E9C+nOmkOf0406vNFUbGhHzkJwbp9YsLk4w8Zz7QfWKWUsyHiXj8QRphRi2IV1oMIJ6UCzhTI/+NbUqhu2kQ64b+BexQAZJsFahSMHwPB24GeXyEy0XLpsd7OEOiJCRhZdiqsuY7DnjABysHc5yRGFn+b9XsQWDZK+PM+hk2pCs=,iv:2Alwd9mW+5YMoEv7I8Fmf0zMDS/jXctO60jXRNxiPck=,tag:ANjEnjA/oaBrpbAtXlpR0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
