apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:Hy8/yqwbXQzv3NMyBU1AkOw3djR/iVvdF3BrSAMaPiDxpAlLEOZr9A==,iv:iQgGo+WINWdu9ZsRbDbEr5TfJIU4LYrTXRDhlcuvzTE=,tag:Tb2itKHzzYUQB4doGCje0w==,type:str]
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZlJBOVB2M2VVR2tRWCtp
            ZCtoV3VxM295OUFWcGl3aVZubUdkTE8yZWtzCkZzbmdscktuVG1qRWJMS2pMcmhB
            VVdZTkIyQWUxZjNGS1AyL0tTdkJ3bmsKLS0tIDVQdTM5aHpmZzdtVERCVlV5UUxw
            QzdKWU4wOHZEa1lLTnFpcVd4YkQ0QncKL11nvOr/KWW1MLe5h1wHbBtNTrHhm5KD
            1XGkQm67x/StoeHkoWS8Rp1kI29t2/rg93mfMv27CuozyzS3uBVFog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEpaVlJlMFQwWEtPbzZX
            VDVKd05sRjBLVm9xbCtQd1J0S285NzVOZURJCi9KY0pobStYbER0VW00YXo1M3Q0
            VVZaKzZNTE9VTDRteGg5d1N2R1RkUTgKLS0tIGtRanEza01aQjRTWjdJa2cxOFpx
            SURGTXJ1TVYwbmhnQTdWSnpuazB0aUUKmVDYLguDhUaEGas1KX/0ExMcwBzAj/KK
            h9MHEYcv/kHGnWciCRPIJr/YZdvybOuaq9gFiuw959kwjuy4AcWH/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T16:22:42Z"
    mac: ENC[AES256_GCM,data:w+WeclMXeVgl5i9eCHLYmErPn7w/4adLIuQFyDtP/pVhKnjdZOx+1eS9aG3K9lbkllBkXKB4eRGl0x7p8LfnV+VSkRS13sE5ezHbI8uJMdpd0LFbdl+hX6ocdyllye8iLhX1yJazCBdSb/AEEtM5bp4uS6B1RLIgVASqEqgmqI8=,iv:+lEzBs51d94h3kHpMI0SYc7nd+RKibocy9tIqlbrF9k=,tag:koVYl/W1OqWryrMj40tDNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
