#---
#apiVersion: helm.cattle.io/v1
#kind: HelmChartConfig
#metadata:
#  name: traefik
#  namespace: kube-system
#spec:
#  valuesContent: |-
#    middlewares:
#      redirect-https:
#        redirectScheme:
#          scheme: https
#          permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingressclass.kubernetes.io/is-default-class: true
spec:
  controller: traefik.io/ingress-controller
