---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs
allowVolumeExpansion: true
parameters:
  recordsize: "128k"
  compression: "zstd"
  dedup: "off"
  fstype: "zfs"
  poolname: "zroot/k8s"
  mountOptions: "noatime" # optional
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
