replicaCount: 1

images:
  rclone:
    repository: rclone/rclone
    pullPolicy: IfNotPresent
    tag: "latest"
  minioclient:
    repository: minio/mc
    pullPolicy: IfNotPresent
    tag: "latest"

# Ingress for public access (needed because the velero client will query it directly, from outside the cluster)
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: velero-encrypt.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: velero-encrypt.example.com
      hosts:
        - velero-encrypt.example.com

app:
  # Encryption key used by rclone
  encryptionKeySecret: "velero-encrypt-key"
  # Credentials to authenticate to rclone s3 server
  in:
    secret: velero-encrypt-in
    s3AccessKey: "s3AccessKey"
    s3SecretKey: "s3SecretKey"
    # Will create this fake bucket in the encrypted S3
    bucket: "fakebucket"
  # Credentials to authenticate to destination s3 server
  out:
    secret: velero-encrypt-out
    provider: "Minio"
    endpoint: "https://restic.example.com"
    region: "us-east-1"
    bucket_and_prefix: "/server1/k8s"
    s3AccessKey: "FAKE_REMOTE_ACCESS_KEY"
    s3SecretKey: "s3SecretKey"
